import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";

import Head from "next/head";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Online-Sekretariat</title>
        <meta
          name="description"
          content="Das Online-Sekretariat für Privatpersonen"
        />
      </Head>

      <body>
        <div className="flex min-h-screen bg-gray-100">
          <Navbar />
          <main className="flex-1 md:p-8 pt-20 p-8 md:ml-64">{children}</main>
        </div>
      </body>
    </html>
  );
}
